// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrashMailPanda.Providers.Storage;

#nullable disable

namespace TrashMailPanda.Providers.Storage.Migrations
{
    [DbContext(typeof(TrashMailPandaDbContext))]
    [Migration("20260317192841_AddGmailTrainingDataSchema")]
    partial class AddGmailTrainingDataSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.AppConfigEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_config", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.ClassificationHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("BatchId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("batch_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("classification");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_id");

                    b.Property<string>("ReasonsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reasons");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAction")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_action");

                    b.Property<string>("UserFeedback")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_feedback");

                    b.HasKey("Id");

                    b.HasIndex("EmailId")
                        .HasDatabaseName("idx_classification_email");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_classification_timestamp");

                    b.ToTable("classification_history", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.EmailArchiveEntry", b =>
                {
                    b.Property<string>("EmailId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderTagsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeEstimate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Snippet")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFolder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserCorrected")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmailId");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("idx_email_archive_archived_at");

                    b.HasIndex("UserCorrected")
                        .HasDatabaseName("idx_email_archive_user_corrected");

                    b.ToTable("email_archive", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.EmailFeatureVector", b =>
                {
                    b.Property<string>("EmailId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyTextShort")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ContactStrength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DkimResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DmarcResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmailAgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<float>("EmailSizeLog")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureSchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HasAttachments")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HasListUnsubscribe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HasTrackingPixel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HourReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InUserBlacklist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InUserWhitelist")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsForwarded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsImportant")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsInInbox")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsReplied")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsReply")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IsStarred")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabelCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LinkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SemanticEmbeddingJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderCategory")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderFrequency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderKnown")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpfResult")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubjectLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubjectText")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThreadMessageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TopicClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicDistributionJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnsubscribeLinkInBody")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserCorrected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WasInSpam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WasInTrash")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmailId");

                    b.HasIndex("ExtractedAt")
                        .HasDatabaseName("idx_email_features_extracted_at");

                    b.HasIndex("FeatureSchemaVersion")
                        .HasDatabaseName("idx_email_features_schema_version");

                    b.HasIndex("UserCorrected")
                        .HasDatabaseName("idx_email_features_user_corrected");

                    b.ToTable("email_features", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.EmailMetadataEntity", b =>
                {
                    b.Property<string>("EmailId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("email_id");

                    b.Property<string>("BulkKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("bulk_key");

                    b.Property<string>("Classification")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("classification");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL")
                        .HasColumnName("confidence");

                    b.Property<string>("FolderId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_id");

                    b.Property<string>("FolderName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("folder_name");

                    b.Property<DateTime?>("LastClassified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_classified");

                    b.Property<string>("ProcessingBatchId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("processing_batch_id");

                    b.Property<string>("ReasonsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("reasons");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_date");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_email");

                    b.Property<string>("SenderName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_name");

                    b.Property<string>("Subject")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<string>("UserAction")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_action");

                    b.Property<DateTime?>("UserActionTimestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_action_timestamp");

                    b.HasKey("EmailId");

                    b.HasIndex("Classification")
                        .HasDatabaseName("idx_email_classification");

                    b.HasIndex("UserAction")
                        .HasDatabaseName("idx_email_user_action");

                    b.ToTable("email_metadata", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.EncryptedCredentialEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("encrypted_value");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.HasKey("Key");

                    b.ToTable("encrypted_credentials", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.EncryptedTokenEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedToken")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("encrypted_token");

                    b.HasKey("Provider");

                    b.ToTable("encrypted_tokens", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.FeatureSchema", b =>
                {
                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Version");

                    b.ToTable("feature_schema_versions", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.LabelAssociationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsContextFeature")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrainingSignal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmailId")
                        .HasDatabaseName("idx_label_assoc_email");

                    b.HasIndex("EmailId", "LabelId")
                        .IsUnique()
                        .HasDatabaseName("idx_label_assoc_unique");

                    b.HasIndex("LabelId", "IsTrainingSignal")
                        .HasDatabaseName("idx_label_assoc_label");

                    b.ToTable("label_associations", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.LabelTaxonomyEntity", b =>
                {
                    b.Property<string>("LabelId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("LabelId");

                    b.HasIndex("UsageCount")
                        .HasDatabaseName("idx_label_taxonomy_usage");

                    b.HasIndex("AccountId", "LabelType")
                        .HasDatabaseName("idx_label_taxonomy_account");

                    b.ToTable("label_taxonomy", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.ScanProgressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderProgressJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("HistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastProcessedEmailId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalEstimate")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Status")
                        .HasDatabaseName("idx_scan_progress_account_status");

                    b.ToTable("scan_progress", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.StorageQuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArchiveBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ArchiveCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CurrentBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeatureBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FeatureCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCleanupAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastMonitoredAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("LimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserCorrectedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("storage_quota", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.TrainingEmailEntity", b =>
                {
                    b.Property<string>("EmailId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassificationSignal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderOrigin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForwarded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReplied")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawLabelIds")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<float>("SignalConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("SubjectPrefix")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThreadId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("EmailId");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_training_emails_account");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("idx_training_emails_last_seen");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("idx_training_emails_thread");

                    b.HasIndex("ClassificationSignal", "IsValid")
                        .HasDatabaseName("idx_training_emails_signal");

                    b.ToTable("training_emails", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.UserRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_key");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_type");

                    b.Property<string>("RuleValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("user_rules", (string)null);
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.LabelAssociationEntity", b =>
                {
                    b.HasOne("TrashMailPanda.Providers.Storage.Models.TrainingEmailEntity", "TrainingEmail")
                        .WithMany("LabelAssociations")
                        .HasForeignKey("EmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrashMailPanda.Providers.Storage.Models.LabelTaxonomyEntity", "LabelTaxonomy")
                        .WithMany("LabelAssociations")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabelTaxonomy");

                    b.Navigation("TrainingEmail");
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.LabelTaxonomyEntity", b =>
                {
                    b.Navigation("LabelAssociations");
                });

            modelBuilder.Entity("TrashMailPanda.Providers.Storage.Models.TrainingEmailEntity", b =>
                {
                    b.Navigation("LabelAssociations");
                });
#pragma warning restore 612, 618
        }
    }
}
